信用证业务信息报文信息记录	IPBLHSP		UPRR
	IPDCDHP		UPRR
	IPDCHSP		UPRR
垫款业务信息报文信息记录	IPDCDHP		UPRR
保函业务信息报文信息记录	IPDCDHP		UPRR
	IPDCHSP		UPRR
	IP@DCMP		UPRR
贷款业务信息报文信息记录-LS/OD	SSGHCLP		UPRR
	SS@AILP		EAST
	LSACMSP		UPRR
	DCACMSP		UPRR
	DDACMSP		UPRR
	LS@AMSP		UPRR
	LP@STDP		UPRR
	SS@CRGP		UPRR
	LSTNJNP 		UPRR
