TEst
Test

SELECT
  ALL       DIGITS(DPACB) AS BRANCH, DIGITS(DPACS) AS SERIAL, DIGITS(DPACX) AS
            SUFFIX, T01.DPTMZ1, T01.DPOVFM, T01.DPDLNO, T01.DPSQNO, T01.DPSSCD,
            T01.DPDLCD, T01.DPTRCD, T01.DPSYRE, T01.DPOREI, T01.DPFWDI,
            T01.DPIMTY, T01.DPIMID, T01.DPTTID, T01.DPCPWS, T01.DPCPUS,
            T01.DPCPDT, T01.DPCPTM, T01.DPAVWS, T01.DPAVUS, T01.DPAVDT,
            T01.DPAVTM, T01.DPPSTS, T01.DPMSID, T01.DPSVLV, T01.DPTCTC,
            T01.DPTGMA, T01.DPTACB, T01.DPPSDT, T01.DPINBI, T01.DPTRNC,
            T01.DPDCG, T01.DPDCB, T01.DPDCS, T01.DPCTCD, T01.DPGMAB, T01.DPACB,
            T01.DPACS, T01.DPACX, T01.DPAPTY, T01.DPCYCD, T01.DPRTRA,
            T01.DPLTRA, T01.DPTEXR, T01.DPSNPR, T01.DPVLDT, T01.DPFADT,
            T01.DPCQNO, T01.DPNAR1, T01.DPNAR2, T01.DPNAR3, T01.DPNAR4,
            T01.DPBLBL, T01.DPBLST, T01.DPRTCR, T01.DPPASI, T01.DPPGSI,
            T01.DPBIIN, T01.DPPAIN, T01.DPTRSN, T01.DPBCR1, T01.DPBCR2,
            T01.DPEXPF, T01.DPPYIO, T01.DPXCCY, T01.DPXTRA, T01.DPDS50,
            T01.DPTRSR, T01.DPDAUE, T01.DPCTXR, T01.DPDOOE, T01.DPOCWS,
            T01.DPODNO, T01.DPESTS, T01.DPTTHD, T01.DPCLVN, T01.DPHOLM,
            T01.DPEXSF, T01.DPCRDO, T01.DPTATN
  FROM      AOCHUBFP/DDTNJNP T01 CROSS JOIN
            AOCHUBFP/SSDATEP T02
  WHERE     SUBSTR(DIGITS(DPPSDT),1,6) = SUBSTR(DIGITS(XSLPDT),1,6)
  
  
  SELECT
  ALL       T02.AACGRP, T01.ZGCTCD, T01.ZGDCG, T01.ZGDCB, T01.ZGDCS, T01.ZGGHCL
,           T01.ZGCSFN, T01.ZGMKS1, T01.ZGDTAD, T01.ZGCRDO, T01.ZGCAST
  FROM      AOCHUBFP/SSCUSTP T01 CROSS JOIN
            AOCHUBFP/SSGHCGP T02 CROSS JOIN
            AOCHUBFP/SSDATEP T03
  WHERE     ZGGHCL = AAGHCL
    AND(    DAYS(SUBSTR(DIGITS(XSTDDT),1,4) CONCAT '-' CONCAT SUBSTR(DIGITS(
            XSTDDT),5,2) CONCAT '-' CONCAT SUBSTR(DIGITS(XSTDDT),7,2))-DAYS(
            SUBSTR(DIGITS(ZGDTAD),1,4) CONCAT '-' CONCAT SUBSTR(DIGITS(ZGDTAD)
            ,5,2) CONCAT '-' CONCAT SUBSTR(DIGITS(ZGDTAD),7,2)) > 7
    AND     AACGRP LIKE 'C%')
  ORDER BY  T01.ZGDCG ASC, T02.AACGRP ASC
  SELECT
  ALL       T01.AACGRP, T01.ZGCTCD, T01.ZGDCG, T01.ZGDCB, T01.ZGDCS, T01.ZGGHCL
,           T01.ZGCSFN, T01.ZGMKS1, T01.ZGDTAD, T01.ZGCRDO, T01.ZGCAST,
            T02.DFACB, T02.DFACS, T02.DFACX, T02.DFAPTY
  FROM      AOCHUBQSY/TEMPBANKX T01 CROSS JOIN
            AOCHUBFP/DDACMSP T02 CROSS JOIN
            AOCHUBFP/SSDATEP T03
  WHERE     ZGDCB = DFDCB
    AND     ZGDCS = DFDCS
    AND(    DAYS(SUBSTR(DIGITS(XSTDDT),1,4) CONCAT '-' CONCAT SUBSTR(DIGITS(
            XSTDDT),5,2) CONCAT '-' CONCAT SUBSTR(DIGITS(XSTDDT),7,2))-DAYS(
            SUBSTR(DIGITS(DFDTAO),1,4) CONCAT '-' CONCAT SUBSTR(DIGITS(DFDTAO)
            ,5,2) CONCAT '-' CONCAT SUBSTR(DIGITS(DFDTAO),7,2)) < 7
    AND     DFDTAO <> 0)
